### ISSUE TITLE
extension/package.json not found inside zip. on Visual Studio Code 1.32.1

### ISSUE THREAD

**Issue by nwavesu** [Microsoft/vsts-ibm-websphere-extension#18]
I tried to install https://marketplace.visualstudio.com/items?itemName=ms-vsts.ibm-websphere&referrer=https%3A%2F%2Fapp.vssps.visualstudio.com%2F_signedin%3Frealm#overview

Visual Studio Code > Extensions > More actions... > Install from VSIX...

![image](https://user-images.githubusercontent.com/20675496/54283911-ab75f480-45a7-11e9-91b0-50d0a1e7efd8.png)

![image](https://user-images.githubusercontent.com/20675496/54283882-9b5e1500-45a7-11e9-8bd4-4f3a3f551633.png)

**Comment by yacaovsnc** [comment]
This isn't a vscode extension.  This is for [Azure DevOps.](https://azure.microsoft.com/en-us/services/devops/)

**Comment by nwavesu** [comment]
Can you please tell me if exists a solution to integrate WebSphere Application Server with Visual Studio Code?

**Comment by yacaovsnc** [comment]
The [marketplace for vscode](https://marketplace.visualstudio.com/vscode) is a good place to start your search.
