### ISSUE TITLE
This extension is overrated, any update pleaase?

### ISSUE THREAD

**Issue by xdie** [Microsoft/vsts-ibm-websphere-extension#9]
I try with the extension but doesn't works, the stdout from commands it is missed.

I tried putting console.log in stdout

`C:\Windows\system32\cmd.exe /D /S /C "C:\IBM\WebSphere\AppServer\profiles\AppSrv03\bin\wsadmin.bat -username xxxx -password xx-host xxxx -port 8882 -conntype SOAP -c "AdminConfig.getid('/Deployment:cc/');""
{"type":"Buffer","data":[]}
{"code":0,"stdout":"","stderr":""}
Not found app cc, install.
C:\Windows\system32\cmd.exe /D /S /C "C:\IBM\WebSphere\AppServer\profiles\AppSrv03\bin\wsadmin.bat -username xxxx -password xx -host xxxx -port 8882 -conntype SOAP -c "AdminApp.update('cc', 'app', '[-operation update -contents C:/agent/_work/1/s/dist/ear/xxx-jndi.ear ]'); AdminConfig.save();""`

Please any can helpme?

**Comment by xdie** [comment]
Sorry, it was permissions problems.
When update app works ok,  but when install app, syntax error any ideas?

**Comment by xdie** [comment]
If I delete this param -MapWebModToVH [["${webModule}" "${uri}" "${virtualHost}"]] from the arguments works fine, any ideas? Thanks Advance

**Comment by stephenmichaelf** [comment]
@yacaovsnc Could you help with this?

**Comment by xdie** [comment]
No worries @stephenmichaelf I use python scripts for IBM, and I created fork from this extension, Thanks!
